### ISSUE TITLE
valid_parentheses(), pytest

### ISSUE THREAD

**Issue by MatejVeselUCLL** [ucll-programming/course-material#105]
file: exercises/loops/test-valid-parentheses.py
The below code passes, although it's incorrect.
```python
def count(char, string):
    n = 0
    for i in string:
        if i == char:
            n += 1
    return n

# Fails for argument "))((", which is not in the pytest.
def valid_parentheses(string):
    if string.endswith(")("):
        return False
    return count("(", string) == count(")", string)
```

**Comment by fvogels** [comment]
Added a few thousand (generated) tests. Your code now fails in 187 cases.

**Comment by MatejVeselUCLL** [comment]
Ok.... D

**Comment by fvogels** [comment]
I hope my comment didn't come across as irritation; your feedback is definitely appreciated.

I typically try to go for robust tests, but clearly my selection of test cases was rather easily fooled in the case of this exercise. So instead I simply decided to generate as many inputs that could be checked in a few seconds, thereby making it much less likely to produce false positives.
