### ISSUE TITLE
Dictionaries - Loopup Default: (not) enough eggs

### ISSUE THREAD

**Issue by karenbaerts** [ucll-programming/course-material#114]
Ik vermoed dat 

     if pantry['eggs'] >= 4:
         # Enough eggs

moet veranderd worden in

     if pantry['eggs'] <= 4:
         # Enough eggs

of

     if pantry['eggs'] >= 4:
         # Not enough eggs

**Comment by brechtnelye** [comment]
You intend to bake some dessert and need to know if you have enough eggs. The dessert requires four eggs, so you perform the following check:

if pantry['eggs'] >= 4:
True --> # enough eggs
False --> # not enough eggs 

Aangezien je voor een cake minstens 4 eieren nodig hebt.

**Comment by karenbaerts** [comment]
Oeps, ik had in de rapte pastry verondersteld ipv pantry... Ik dacht dus in de omgekeerde richting, nevermind!
