### ISSUE TITLE
tuples - increase version 

### ISSUE THREAD

**Issue by AxlNuyens** [ucll-programming/course-material#116]
in solutions.py staat een fout:
def increase_version(version, breaking_change, new_features):
    a, b, c = version
    if breaking_change:
        return (a + 1, 0, 0)
    elif new_features: 
        **return (a, b + 1, 0)**
    else: 
        return (a, b, c + 1)
in new features staat a,b+1, 0 terwijl het a, b+1, c moet zijn

**Comment by brechtnelye** [comment]
following the example it shows when a new feature is implemented, b increases with 1 and, c is set to zero.
