### ISSUE TITLE
Classroom repo change main to master and avoid conflict with master/main during install

### ISSUE THREAD

**Issue by brechtnelye** [ucll-programming/course-material#66]

**Comment by fvogels** [comment]
How? :-)

**Comment by brechtnelye** [comment]
account -> settings -> repositories -> change 'main' into 'master' 
change default branch from main to master?  with the -M command or rebase?

**Comment by brechtnelye** [comment]
Seems master is depreciated and main is pushed for usage. So I closed this issue. 
apparently master is considered racist...
