### ISSUE TITLE
Chapter Boolean Exercise Free Ticket Issue

### ISSUE THREAD

**Issue by Luma48** [ucll-programming/course-material#69]
In the Chapter Boolean -> Exercise Free Ticket there is incorrect information given to the user.  The exercise states that: "A bus ticket is free for anyone under 12 or over 65." This is incorrect because for my code to work I had to write "if age < 12 or age >= 65:" So they exercise should say: "A bus ticket is free for anyone under 12 or 65 and over." The image used for the exercise is also misleading because it shows that 6 should return False which makes no sense because it is lower than 12.
![Issue](https://github.com/ucll-programming/course-material/assets/81435074/0978613e-16aa-4b5e-802a-318a2fbcd83a)

**Comment by brechtnelye** [comment]
Already fixed with previous PR? 
I'll add a new PR tomorrow

**Comment by brechtnelye** [comment]
Can be closed, fixed by new PR

**Comment by fvogels** [comment]
Has indeed been fixed, closing.
