### ISSUE TITLE
a statement, which means you cannot but it inside something else

### ISSUE THREAD

**Issue by karenbaerts** [ucll-programming/course-material#80]
I'm not really sure what is meant here :)

**Comment by brechtnelye** [comment]
a = b is a statement, which means you cannot put it inside something else. For example print(a = b) is invalid. An assignment always belongs on a line of its own.

a := b is an expression and belongs "inside" something else. Writing a := b on a separate line will cause an error.

**Comment by karenbaerts** [comment]
Thanks, I noticed the line of text that wasn't really clear to me has now been changed.
