### ISSUE TITLE
Unclear Instructions and a Mistake

### ISSUE THREAD

**Issue by MatejVeselUCLL** [ucll-programming/course-material#84]
file: exercises\booleans\assignment-free-ticket.en.md

It is not clear in the instructions that the interval for free tickets is ` age < 12 and age >= 65` and **not** `age <= 12 and age >= 65`

In the usage example, the return of the function `free_ticket(6)` is `False`, which is a mistake.

**Comment by brechtnelye** [comment]
That is already fixed, I recommend you to do a git pull upstream

**Comment by MatejVeselUCLL** [comment]
Thank you. I apologize for unnecessary issue.
