### ISSUE TITLE
Pytest Instructions unclear

### ISSUE THREAD

**Issue by MatejVeselUCLL** [ucll-programming/course-material#87]
page: https://ucll-programming.github.io/course-material/workflow/pytest.html

From the explanation, one assumes the syntax for testing a function is `pytest test-FUNCTIONNAME.py`, e.g. `pytest test-free_ticket.py`. Apparently that is not the case, since the correct usage is `pytest test-free-ticket.py`, but the function name is `free_ticket()`, not `free-ticket()`.

**Comment by brechtnelye** [comment]
I don't think this is a big issue since you can easily see in the file structure the names of the test and with TAB for autocomplete the path. You shouldn't run into any problems.

**Comment by MatejVeselUCLL** [comment]
Indeed, although for beginners it might be confusing. If nothing else, maybe add a note about what you said to the page with Pytest instructions.
