### ISSUE TITLE
Booleans Earlier Bug

### ISSUE THREAD

**Issue by MatejVeselUCLL** [ucll-programming/course-material#92]
file: exercises/booleans/test-earlier.py

The code below should pass the test, sadly that's not the case.
```
def earlier(h1, m1, h2, m2):
    return h1 < h2 or (h1 == h2 and m1 <= m2)
```

**Comment by brechtnelye** [comment]
I believe you are convinced that code should pass the test. 
But if you run pytest -x test-earlier.py 
You will get information on why your code is not correct. 

Happy bug searching and enjoy coding!

**Comment by MatejVeselUCLL** [comment]
`AssertionError: 00:00 should be earlier than 00:00`

Shouldn't it say `AssertionError: 00:00 should not be earlier than 00:00`?

**Comment by brechtnelye** [comment]
```
h1 = 0, m1 = 0, h2 = 0, m2 = 0, expected = False

    @pytest.mark.timeout(1)
    @pytest.mark.parametrize("h1, m1, h2, m2, expected", [
        (k1 // 60, k1 % 60, k2 // 60, k2 % 60, k1 < k2)
        for k1 in range(0, 12 * 60, 25)
        for k2 in range(0, 12 * 60, 25)
    ])
    def test_earlier(h1, m1, h2, m2, expected):
        actual = student.earlier(h1, m1, h2, m2)
>       assert expected == actual, f'{h1:02}:{m1:02} should be earlier than {h2:02}:{m2:02}'
E       AssertionError: 00:00 should be earlier than 00:00
E       assert False == True
```

The first line tells you it's expected to be False

E The assertionError: says that time x should be earlier than time y (this line says what it should be time x should be earlier than time y) 
E assert False == True (meaning your code says 00:00 is earlier than 00:00. Which is not the case.

**Comment by MatejVeselUCLL** [comment]
Ah ok. I think I understand. Thanks you.
