### ISSUE TITLE
Conditionals Elif Explanation

### ISSUE THREAD

**Issue by MatejVeselUCLL** [ucll-programming/course-material#93]
file: exercises/conditionals/explanation-elif.en.md

At the end of the third code snippet there is a little mistake. `C` should be `instruction C`.

Are `False` values in the if-elif chain diagram positioned at the correct place? Shouldn't they be on the arrow between conditions? I'm using latest Firefox Developer Edition.

![image](https://github.com/ucll-programming/course-material/assets/145494857/20f7c7ac-4808-41e8-8dbf-38b7751b6979)

**Comment by brechtnelye** [comment]
which browser do you use?

**Comment by brechtnelye** [comment]
Try running it in chrome, its probably firefox

**Comment by MatejVeselUCLL** [comment]
C at the bottom should be `instruction C`

![image](https://github.com/ucll-programming/course-material/assets/145494857/215b6982-9017-485d-8040-ad7461e6311f)

**Comment by brechtnelye** [comment]
Thank you for the clarification! I'll change that.

**Comment by brechtnelye** [comment]
fixed
